[build]
  publish = "public"
  command = "hugo -t cupper-hugo-theme"

[build.environment]
  HUGO_VERSION = "0.71.1"
  HUGO_THEME = "cupper-hugo-theme"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.com/"